"""add_api_key_pool

Revision ID: 1d6d57d01fe7
Revises: bb403d12a8ba
Create Date: 2026-08-24 15:07:23.799972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6d57d01fe7'
down_revision: Union[str, None] = 'bb403d12a8ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_pool',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_config_id', sa.String(length=36), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_config_id'], ['ai_model_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_pool_model_config_id'), 'api_key_pool', ['model_config_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_key_pool_model_config_id'), table_name='api_key_pool')
    op.drop_table('api_key_pool')
    # ### end Alembic commands ###
