"""add auth fields

Revision ID: 297e9fb09086
Revises: b98eb8e5b639
Create Date: 2026-04-14 03:38:42.658089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '297e9fb09086'
down_revision: Union[str, None] = 'b98eb8e5b639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=200), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.String(length=200),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.String(length=200),
               nullable=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
