"""add_queue_tasks

Revision ID: bb403d12a8ba
Revises: q3r4s5t6u7v8
Create Date: 2026-08-24 12:41:35.833752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb403d12a8ba'
down_revision: Union[str, None] = 'q3r4s5t6u7v8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('profile_name', sa.String(length=200), nullable=True),
    sa.Column('doc_style_id', sa.String(length=36), nullable=True),
    sa.Column('job_source_url', sa.Text(), nullable=True),
    sa.Column('job_url', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=300), nullable=True),
    sa.Column('job_title', sa.String(length=300), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doc_style_id'], ['doc_styles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_tasks_created_at'), 'queue_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_queue_tasks_status'), 'queue_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_queue_tasks_user_id'), 'queue_tasks', ['user_id'], unique=False)
    op.create_index('ix_queue_tasks_user_order', 'queue_tasks', ['user_id', 'order', 'created_at'], unique=False)
    op.create_index('ix_queue_tasks_user_status', 'queue_tasks', ['user_id', 'status'], unique=False)
    op.alter_column('applications', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('applications', 'completion_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('applications', 'total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.drop_index('ix_batch_jobs_created_at', table_name='batch_jobs')
    op.drop_constraint('call_stages_value_key', 'call_stages', type_='unique')
    op.create_unique_constraint('uq_call_stages_value', 'call_stages', ['value'])
    op.drop_column('experiences', 'location')
    op.drop_column('experiences', 'description')
    op.alter_column('knowledge_bases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_profiles_doc_style_id'), 'profiles', ['doc_style_id'], unique=False)
    op.alter_column('system_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('token_pricing', 'effective_from',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('users', sa.Column('queue_running', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'bidder'::character varying"))
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'bidder'::character varying"))
    op.drop_column('users', 'queue_running')
    op.alter_column('token_pricing', 'effective_from',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('system_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_profiles_doc_style_id'), table_name='profiles')
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('knowledge_bases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('experiences', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('experiences', sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint('uq_call_stages_value', 'call_stages', type_='unique')
    op.create_unique_constraint('call_stages_value_key', 'call_stages', ['value'])
    op.create_index('ix_batch_jobs_created_at', 'batch_jobs', ['created_at'], unique=False)
    op.alter_column('applications', 'total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('applications', 'completion_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('applications', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index('ix_queue_tasks_user_status', table_name='queue_tasks')
    op.drop_index('ix_queue_tasks_user_order', table_name='queue_tasks')
    op.drop_index(op.f('ix_queue_tasks_user_id'), table_name='queue_tasks')
    op.drop_index(op.f('ix_queue_tasks_status'), table_name='queue_tasks')
    op.drop_index(op.f('ix_queue_tasks_created_at'), table_name='queue_tasks')
    op.drop_table('queue_tasks')
    # ### end Alembic commands ###
